### PR TITLE
Add note to README

### PR DESCRIPTION
**Pull request by canndrew**

### CODE REVIEW

**Comment by jhasse** [comment]
This will add a commit with 2017 as its date and might actually result in people thinking this repo is still being used :/

Can the note be added to the description on GitHub? And my repo as the URL?

**Comment by jeremyletang** [comment]
true, will do.

**Comment by jhasse** [comment]
Thanks :)

**Comment by jeremyletang** [comment]
You are welcome.
@canndrew I close this PR, thank you. I think the mention in the description should be sufficient.

**Pull request closed without merging**
